#!/bin/bash
cd $CMSSW_BASE/src/CSCUCLA/CSCDigiTuples/test/
	
sbatch TestJobs/Send_RunAna_0.slrm
sbatch TestJobs/Send_RunAna_1.slrm
sbatch TestJobs/Send_RunAna_2.slrm
sbatch TestJobs/Send_RunAna_3.slrm
sbatch TestJobs/Send_RunAna_4.slrm
sbatch TestJobs/Send_RunAna_5.slrm
sbatch TestJobs/Send_RunAna_6.slrm
sbatch TestJobs/Send_RunAna_7.slrm
sbatch TestJobs/Send_RunAna_8.slrm
sbatch TestJobs/Send_RunAna_9.slrm
sbatch TestJobs/Send_RunAna_10.slrm
sbatch TestJobs/Send_RunAna_11.slrm
sbatch TestJobs/Send_RunAna_12.slrm
sbatch TestJobs/Send_RunAna_13.slrm
sbatch TestJobs/Send_RunAna_14.slrm
sbatch TestJobs/Send_RunAna_15.slrm
sbatch TestJobs/Send_RunAna_16.slrm
sbatch TestJobs/Send_RunAna_17.slrm
sbatch TestJobs/Send_RunAna_18.slrm
sbatch TestJobs/Send_RunAna_19.slrm
sbatch TestJobs/Send_RunAna_20.slrm
sbatch TestJobs/Send_RunAna_21.slrm
sbatch TestJobs/Send_RunAna_22.slrm
sbatch TestJobs/Send_RunAna_23.slrm
sbatch TestJobs/Send_RunAna_24.slrm
sbatch TestJobs/Send_RunAna_25.slrm
sbatch TestJobs/Send_RunAna_26.slrm
sbatch TestJobs/Send_RunAna_27.slrm
sbatch TestJobs/Send_RunAna_28.slrm
sbatch TestJobs/Send_RunAna_29.slrm
sbatch TestJobs/Send_RunAna_30.slrm
sbatch TestJobs/Send_RunAna_31.slrm
sbatch TestJobs/Send_RunAna_32.slrm
sbatch TestJobs/Send_RunAna_33.slrm
sbatch TestJobs/Send_RunAna_34.slrm
sbatch TestJobs/Send_RunAna_35.slrm
sbatch TestJobs/Send_RunAna_36.slrm
sbatch TestJobs/Send_RunAna_37.slrm
sbatch TestJobs/Send_RunAna_38.slrm
sbatch TestJobs/Send_RunAna_39.slrm
sbatch TestJobs/Send_RunAna_40.slrm
sbatch TestJobs/Send_RunAna_41.slrm
sbatch TestJobs/Send_RunAna_42.slrm
sbatch TestJobs/Send_RunAna_43.slrm
sbatch TestJobs/Send_RunAna_44.slrm
sbatch TestJobs/Send_RunAna_45.slrm
sbatch TestJobs/Send_RunAna_46.slrm
sbatch TestJobs/Send_RunAna_47.slrm
sbatch TestJobs/Send_RunAna_48.slrm
sbatch TestJobs/Send_RunAna_49.slrm
sbatch TestJobs/Send_RunAna_50.slrm
sbatch TestJobs/Send_RunAna_51.slrm
sbatch TestJobs/Send_RunAna_52.slrm
sbatch TestJobs/Send_RunAna_53.slrm
sbatch TestJobs/Send_RunAna_54.slrm
sbatch TestJobs/Send_RunAna_55.slrm
sbatch TestJobs/Send_RunAna_56.slrm
sbatch TestJobs/Send_RunAna_57.slrm
sbatch TestJobs/Send_RunAna_58.slrm
sbatch TestJobs/Send_RunAna_59.slrm
sbatch TestJobs/Send_RunAna_60.slrm
sbatch TestJobs/Send_RunAna_61.slrm
sbatch TestJobs/Send_RunAna_62.slrm
sbatch TestJobs/Send_RunAna_63.slrm
sbatch TestJobs/Send_RunAna_64.slrm
sbatch TestJobs/Send_RunAna_65.slrm
sbatch TestJobs/Send_RunAna_66.slrm
sbatch TestJobs/Send_RunAna_67.slrm
sbatch TestJobs/Send_RunAna_68.slrm
sbatch TestJobs/Send_RunAna_69.slrm
sbatch TestJobs/Send_RunAna_70.slrm
sbatch TestJobs/Send_RunAna_71.slrm
sbatch TestJobs/Send_RunAna_72.slrm
sbatch TestJobs/Send_RunAna_73.slrm
sbatch TestJobs/Send_RunAna_74.slrm
sbatch TestJobs/Send_RunAna_75.slrm
sbatch TestJobs/Send_RunAna_76.slrm
sbatch TestJobs/Send_RunAna_77.slrm
sbatch TestJobs/Send_RunAna_78.slrm
sbatch TestJobs/Send_RunAna_79.slrm
sbatch TestJobs/Send_RunAna_80.slrm
sbatch TestJobs/Send_RunAna_81.slrm
sbatch TestJobs/Send_RunAna_82.slrm
sbatch TestJobs/Send_RunAna_83.slrm
sbatch TestJobs/Send_RunAna_84.slrm
sbatch TestJobs/Send_RunAna_85.slrm
sbatch TestJobs/Send_RunAna_86.slrm
sbatch TestJobs/Send_RunAna_87.slrm
sbatch TestJobs/Send_RunAna_88.slrm
sbatch TestJobs/Send_RunAna_89.slrm
sbatch TestJobs/Send_RunAna_90.slrm
sbatch TestJobs/Send_RunAna_91.slrm
sbatch TestJobs/Send_RunAna_92.slrm
sbatch TestJobs/Send_RunAna_93.slrm
sbatch TestJobs/Send_RunAna_94.slrm
sbatch TestJobs/Send_RunAna_95.slrm
sbatch TestJobs/Send_RunAna_96.slrm
sbatch TestJobs/Send_RunAna_97.slrm
sbatch TestJobs/Send_RunAna_98.slrm
sbatch TestJobs/Send_RunAna_99.slrm
sbatch TestJobs/Send_RunAna_100.slrm
sbatch TestJobs/Send_RunAna_101.slrm
sbatch TestJobs/Send_RunAna_102.slrm
sbatch TestJobs/Send_RunAna_103.slrm
sbatch TestJobs/Send_RunAna_104.slrm
sbatch TestJobs/Send_RunAna_105.slrm
sbatch TestJobs/Send_RunAna_106.slrm
sbatch TestJobs/Send_RunAna_107.slrm
sbatch TestJobs/Send_RunAna_108.slrm
sbatch TestJobs/Send_RunAna_109.slrm
sbatch TestJobs/Send_RunAna_110.slrm
sbatch TestJobs/Send_RunAna_111.slrm
sbatch TestJobs/Send_RunAna_112.slrm
sbatch TestJobs/Send_RunAna_113.slrm
sbatch TestJobs/Send_RunAna_114.slrm
sbatch TestJobs/Send_RunAna_115.slrm
sbatch TestJobs/Send_RunAna_116.slrm
sbatch TestJobs/Send_RunAna_117.slrm
sbatch TestJobs/Send_RunAna_118.slrm
sbatch TestJobs/Send_RunAna_119.slrm
sbatch TestJobs/Send_RunAna_120.slrm
sbatch TestJobs/Send_RunAna_121.slrm
sbatch TestJobs/Send_RunAna_122.slrm
sbatch TestJobs/Send_RunAna_123.slrm
sbatch TestJobs/Send_RunAna_124.slrm
sbatch TestJobs/Send_RunAna_125.slrm
sbatch TestJobs/Send_RunAna_126.slrm
sbatch TestJobs/Send_RunAna_127.slrm
sbatch TestJobs/Send_RunAna_128.slrm
sbatch TestJobs/Send_RunAna_129.slrm
sbatch TestJobs/Send_RunAna_130.slrm
sbatch TestJobs/Send_RunAna_131.slrm
sbatch TestJobs/Send_RunAna_132.slrm
sbatch TestJobs/Send_RunAna_133.slrm
sbatch TestJobs/Send_RunAna_134.slrm
sbatch TestJobs/Send_RunAna_135.slrm
sbatch TestJobs/Send_RunAna_136.slrm
sbatch TestJobs/Send_RunAna_137.slrm
sbatch TestJobs/Send_RunAna_138.slrm
sbatch TestJobs/Send_RunAna_139.slrm
sbatch TestJobs/Send_RunAna_140.slrm
sbatch TestJobs/Send_RunAna_141.slrm
sbatch TestJobs/Send_RunAna_142.slrm
sbatch TestJobs/Send_RunAna_143.slrm
sbatch TestJobs/Send_RunAna_144.slrm
sbatch TestJobs/Send_RunAna_145.slrm
sbatch TestJobs/Send_RunAna_146.slrm
sbatch TestJobs/Send_RunAna_147.slrm
sbatch TestJobs/Send_RunAna_148.slrm
sbatch TestJobs/Send_RunAna_149.slrm
sbatch TestJobs/Send_RunAna_150.slrm
sbatch TestJobs/Send_RunAna_151.slrm
sbatch TestJobs/Send_RunAna_152.slrm
sbatch TestJobs/Send_RunAna_153.slrm
sbatch TestJobs/Send_RunAna_154.slrm
sbatch TestJobs/Send_RunAna_155.slrm
sbatch TestJobs/Send_RunAna_156.slrm
sbatch TestJobs/Send_RunAna_157.slrm
sbatch TestJobs/Send_RunAna_158.slrm
sbatch TestJobs/Send_RunAna_159.slrm
sbatch TestJobs/Send_RunAna_160.slrm
sbatch TestJobs/Send_RunAna_161.slrm
sbatch TestJobs/Send_RunAna_162.slrm
sbatch TestJobs/Send_RunAna_163.slrm
sbatch TestJobs/Send_RunAna_164.slrm
sbatch TestJobs/Send_RunAna_165.slrm
sbatch TestJobs/Send_RunAna_166.slrm
sbatch TestJobs/Send_RunAna_167.slrm
sbatch TestJobs/Send_RunAna_168.slrm
sbatch TestJobs/Send_RunAna_169.slrm
sbatch TestJobs/Send_RunAna_170.slrm
sbatch TestJobs/Send_RunAna_171.slrm
sbatch TestJobs/Send_RunAna_172.slrm
sbatch TestJobs/Send_RunAna_173.slrm
sbatch TestJobs/Send_RunAna_174.slrm
sbatch TestJobs/Send_RunAna_175.slrm
sbatch TestJobs/Send_RunAna_176.slrm
sbatch TestJobs/Send_RunAna_177.slrm
sbatch TestJobs/Send_RunAna_178.slrm
sbatch TestJobs/Send_RunAna_179.slrm
sbatch TestJobs/Send_RunAna_180.slrm
sbatch TestJobs/Send_RunAna_181.slrm
sbatch TestJobs/Send_RunAna_182.slrm
sbatch TestJobs/Send_RunAna_183.slrm
sbatch TestJobs/Send_RunAna_184.slrm
sbatch TestJobs/Send_RunAna_185.slrm
sbatch TestJobs/Send_RunAna_186.slrm
sbatch TestJobs/Send_RunAna_187.slrm
sbatch TestJobs/Send_RunAna_188.slrm
sbatch TestJobs/Send_RunAna_189.slrm
sbatch TestJobs/Send_RunAna_190.slrm
sbatch TestJobs/Send_RunAna_191.slrm
sbatch TestJobs/Send_RunAna_192.slrm
sbatch TestJobs/Send_RunAna_193.slrm
sbatch TestJobs/Send_RunAna_194.slrm
sbatch TestJobs/Send_RunAna_195.slrm
sbatch TestJobs/Send_RunAna_196.slrm
sbatch TestJobs/Send_RunAna_197.slrm
sbatch TestJobs/Send_RunAna_198.slrm
sbatch TestJobs/Send_RunAna_199.slrm